[package]
name = "space_minecraft"
version = "0.1.0"
edition = "2021"

[dependencies]
vulkano = "0.32.3"
vulkano-shaders = "0.32.0"
winit = "0.27"
rand = "0.8"
nalgebra = "0.32"
noise = "0.8"